### ISSUE TITLE
关于实验指导书推荐版本与示例所用版本不同

### ISSUE THREAD

**Issue by GeneraluseAI** [Roycent/CC-Labs#3]
在实验一“安装docker”一条中用推荐的方法
`add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"` 
会自动在下载源列表中加入docker-ce的focal发行，但是focal发行的最老版本已经是 19.03.9
并不能直接下载到示例所用的 **18.06.3-ce** 版本，在实验一中影响不大，但是在实验二中示例所用的kubernetes版本过老，并不适配于较新的docker发行版本，可能对实验的操作产生影响，该示例所用版本现在仅在 bionic 发行中仍存在，将以上语句改为
`add-apt-repository "deb [arch=amd64] https://mirrors.ustc.edu.cn/docker-ce/linux/ubuntu bionic stable"`
可能会这个问题有帮助。

**Comment by Roycent** [comment]
Kubernetes部分实验已经过时，我们会在K8S实验开始之前更新此部分的实验手册。事实上在新版的K8S中已经弃用了Docker。
在实验手册更新并正式发布之前不要提前做K8S部分的实验。

**Comment by GeneraluseAI** [comment]
收到，感谢答疑。
